package com.example.nba_stats

class TeamsResources
{
    companion object{
        val teamColors = mapOf(
            "ATL" to R.color.atlanta_hawks,
            "BOS" to R.color.boston_celtics,
            "CHI" to R.color.chicago_bulls,
            "NYK" to R.color.new_york_knicks,
            "PHI" to R.color.philadelphia_76ers,
            "TOR" to R.color.toronto_raptors,
            "CLE" to R.color.cleveland_cavaliers,
            "DET" to R.color.detroit_pistons,
            "IND" to R.color.indiana_pacers,
            "MIL" to R.color.milwaukee_bucks,
            "CHA" to R.color.charlotte_hornets,
            "MIA" to R.color.miami_heat,
            "ORL" to R.color.orlando_magic,
            "WAS" to R.color.washington_wizards,
            "DEN" to R.color.denver_nuggets,
            "MIN" to R.color.minnesota_timberwolves,
            "OKC" to R.color.oklahoma_city_thunder,
            "POR" to R.color.portland_trail_blazers,
            "UTA" to R.color.utah_jazz,
            "GSW" to R.color.golden_state_warriors,
            "LAC" to R.color.la_clippers,
            "LAL" to R.color.los_angeles_lakers,
            "PHX" to R.color.phoenix_suns,
            "SAC" to R.color.sacramento_kings,
            "DAL" to R.color.dallas_mavericks,
            "HOU" to R.color.houston_rockets,
            "MEM" to R.color.memphis_grizzlies,
            "NOP" to R.color.new_orleans_pelicans,
            "SAS" to R.color.san_antonio_spurs,
            "BKN" to R.color.brooklyn_nets
        )

        val teamImages = mapOf(
            "BOS" to R.drawable.bos,
            "POR" to R.drawable.por,
            "LAL" to R.drawable.lal,
            "TOR" to R.drawable.tor,
            "NYK" to R.drawable.nyk,
            "PHI" to R.drawable.phi,
            "MIL" to R.drawable.mil,
            "DEN" to R.drawable.den,
            "CLE" to R.drawable.cle,
            "MEM" to R.drawable.mem,
            "ATL" to R.drawable.atl,
            "UTA" to R.drawable.uta,
            "HOU" to R.drawable.hou,
            "SAC" to R.drawable.sac,
            "IND" to R.drawable.ind,
            "GSW" to R.drawable.gsw,
            "SAS" to R.drawable.sas,
            "WAS" to R.drawable.was,
            "PHX" to R.drawable.phx,
            "CHA" to R.drawable.cha,
            "NOP" to R.drawable.nop,
            "LAC" to R.drawable.lac,
            "MIA" to R.drawable.mia,
            "DET" to R.drawable.det,
            "DAL" to R.drawable.dal,
            "ORL" to R.drawable.orl,
            "MIN" to R.drawable.min,
            "BKN" to R.drawable.bkn,
            "CHI" to R.drawable.chi,
            "OKC" to R.drawable.okc,
        )
    }
}